### ISSUE TITLE
Create from file problems (recently appeared)

### ISSUE THREAD

**Issue by rvencu** [hfig/MAPI#18]
I used the library for about half year without no issues. In the last month or so I started to get fatal errors like this (even after updating the libraries with composer)

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Hfig\MAPI\OLE\Pear\DocumentElement::__construct() must be an instance of OLE_PPS, null given, called in /home/focality/public_html/wp-content/plugins/custom-frm-richard/vendor/hfig/mapi/src/MAPI/OLE/Pear/DocumentFactory.php on line 17 and defined in /home/focality/public_html/wp-content/plugins/custom-frm-richard/vendor/hfig/mapi/src/MAPI/OLE/Pear/DocumentElement.php:23

What I do is simply 
`if ( pathinfo( $filepath, PATHINFO_EXTENSION ) == "msg" ) {
	$ole     = $documentFactory->createFromFile( $filepath );
}`

**Comment by hfig** [comment]
If you look at the code for the ``DocumentFactory::createFromFile()``, you can see it just gets the ``pear/ole`` library to read the file and passes the ``root`` element of the file on to the ``DocumentElement`` class. Your error is caused by ``pear/ole`` not locating a root element in the OLE compound document - ie the input file is invalid. 

Your input hasn't been changed from Outlook MAPI MSG to something actually sane like a plain RFC822 MIME message file (usually given the extension .eml)?

Use [SSView](https://www.mitec.cz/ssv.html) or another tool to verify whether the document is valid. But in either case, the problem would have to be fixed in [``pear/ole``](https://pear.php.net/package/OLE).

**Comment by rvencu** [comment]
Thank you. The SSView tool reports the message file as valid. I will jump to pear/ole issues then.
