### ISSUE TITLE
How to get attachments?

### ISSUE THREAD

**Issue by strtob** [hfig/MAPI#33]
Hi,

Thank you for sharing this great extensions! How can I access the received attachments from $message->getAttachments() in a foreach to save them in php?

Best regards,
Toby

**Comment by hfig** [comment]
This isn't an "issue".

You call ``getAttachments()`` on a message object. Get the attachment's content with ``getData()``. Save it to disk. See the various ``Hfig\MAPI\Mime\Swiftmailer`` classes that do basically this converting a message to MIME format.

This works unless your mail client decided to send you a message with a .doc or .xls or .ppt or the like embedded as a sub-document instead of file attachment. Then it blows up. But hopefully that doesn't actually occur these days (as opposed to c. 1996)
