### ISSUE TITLE
How to get raw MSG contents of MSG attachment

### ISSUE THREAD

**Issue by S-R0** [hfig/MAPI#49]
Lets say I have an msg message called `MSG Level 1.msg` which contains an attachment inside it called `MSG Level 2.msg`.

When I loop over `MSG Level 1.msg` with `getAttachments()`, is there a way to get the contents of `MSG Level 2.msg` in its raw MSG format?

At the moment my application offers a feature to convert an MSG upload to a readable file, whenever the user requests it. I need to be able to get any MSG attachments inside an MSG file and save them separately in their raw MSG format, so I can offer the same feature to nested MSG files.

Is this something thats possible? From what I can tell, the only content options on a `Hfig\MAPI\Message\Message` object are `getBody`, `getBodyRTF` and `getBodyHTML`.

If its not possible, do you know how I might go about achieving this?

Thanks in advance

**Comment by hfig** [comment]
Because this library was written for a limited set of use cases, the answer is "I don't know". What are you getting out of `getAttachments()` now? There are a couple of ways the originating program could have constructed the file -- it could have literally attached it like any other file, or it could have embedded it within the MAPI document (this is, I believe, also true of other OLE compound documents like .doc and .xls). 

If it's the former, you can write it to stream (or file) and then read it in with a new DocumentFactory instance.

If it's the latter, you're probably looking at having to research how this is done and then extend the library. As always: PR's accepted!

**Comment by S-R0** [comment]
The `getAttachments()` function is returning already parsed MSG messages for the attachments.

I've found a way around this for now to solve my problem. Thanks anyway! I'll close this issue!
