### ISSUE TITLE
Failed instalation

### ISSUE THREAD

**Issue by lumber94** [hfig/MAPI#9]
Using version ^1.1 for hfig/mapi
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - hfig/mapi v1.1.1 requires pear/ole ^1.0.0RC5 -> satisfiable by pear/ole[v1.0.0RC5] but these conflict with your requirements or minimum-stability.
    - hfig/mapi v1.1 requires pear/ole ^1.0.0RC5 -> satisfiable by pear/ole[v1.0.0RC5] but these conflict with your requirements or minimum-stability.
    - Installation request for hfig/mapi ^1.1 -> satisfiable by hfig/mapi[v1.1, v1.1.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by lumber94** [comment]
The latest version for now is - https://pear.php.net/package/OLE/download/All 1.0.0RC3

**Comment by lumber94** [comment]
How i can install package ? Thanks

**Comment by hfig** [comment]
Current release is 1.0.0RC5. See their [Github repo](https://packagist.org/packages/pear/ole). The PEAR website is mostly abandoned.

If you ``minimum-stability`` is set in your ``composer.json`` you'll need to relax it to ``RC`` in order to install a release candidate-stability package.

**Comment by lumber94** [comment]
@hfig thanks a lot. It`s work now 👍

**Comment by Tilogorn** [comment]
I ran into the same issue. Do you bother adding your answer to the README? Since it seems that happens to regular installations (PHP 7.2 on Ubuntu 16 here) it would help to find that information directly.

**Comment by hfig** [comment]
The error message from composer tells you what's wrong though?

**Comment by Tilogorn** [comment]
Yes, it does. 

And ten minutes googling the error message unsuccessfully (I've never heard of nor seen the property `minimum-stability` in a `composer.json`) and searching through your `README` and code led me to manually check your open and closed issues, hoping somebody else has had this problem before. Successfully. That's why I thought of a shortcut, to prevent somebody else with a standard installation like mine has to go through this journey.

But it's up to you, just a matter of convenience.

Great library by the way, thanks for your effort and time!

**Comment by hfig** [comment]
Submit a PR and I can merge.
